// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejwqctsxwwqvcvbmrxej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqd3FjdHN4d3dxdmN2Ym1yeGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzAwNTMsImV4cCI6MjA2Mzg0NjA1M30.kXodxaqzcOSzMphbjxkMBnGB9b4AQ0xGVdUChjh0jGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);